### ISSUE TITLE
What example games do we want to make?

### ISSUE THREAD

**Issue by ptrgags** [ptrgags/byte-cards#7]
I used the card game War as an initial example since it's very basic. What other cards do we want to implement as examples as well as ways of testing our API for readability?

**Comment by KarishmaChanglani** [comment]
Good easy game I found that should be good for the version 1: 
- Crazy Eights

How to play: In a two-player game, each player is dealt seven cards. In a game with three or four players, each player is dealt five cards. The rest of the deck goes facedown in a pile, with the top card turned up beside it. This is the discard pile. The player to the left of the dealer discards a card from his hand that matches either the number or suit of the top card in the discard pile. For example, if the card is a five of hearts, he could play any heart or any five. If he does not have a matching card, he continues picking up cards from the deck until he gets one that is playable. Eights are wild and can be put down on any suit. For example, an eight could be played to match a heart. The next player must match their card to the number or suit that the eight was meant to cover. Play continues with players matching the card at the top of the discard pile. The first player to use up all his cards wins. If the deck runs out before the game is over, the discard pile can be used.
